### ISSUE TITLE
字节跳动前端题目数据错了

### ISSUE THREAD

**Issue by Sermonizer** [afatcoder/LeetcodeTop#1]
老哥，前端的链接里面放的都是测试的题，麻烦改一下嗷

**Comment by ErazerControl** [comment]
> 老哥，前端的链接里面放的都是测试的题，麻烦改一下嗷

感谢反馈！已解决~

**Comment by afatcoder** [comment]
> 老哥，前端的链接里面放的都是测试的题，麻烦改一下嗷

感谢反馈！已解决~

**Comment by gotoppp** [comment]
搭配大厂算法课程更香: https://youkewang.top/?s=%E7%AE%97%E6%B3%95

**Comment by Misaka11** [comment]
已收到您发的邮件。本邮件是自动回复。
