### ISSUE TITLE
小程序内使用web-view

### ISSUE THREAD

**Issue by HistoryZhang** [afatcoder/LeetcodeTop#14]
你好，我看了你的小程序，用到了web-view来展示公众号的文章，这个个人小程序现在可以使用web-view来展示关联公众号的文章了么？

**Comment by afatcoder** [comment]
> 你好，我看了你的小程序，用到了web-view来展示公众号的文章，这个个人小程序现在可以使用web-view来展示关联公众号的文章了么？

是可以的。https://developers.weixin.qq.com/miniprogram/dev/component/web-view.html
