### ISSUE TITLE
社招收集到的算法题，麻烦加一下

### ISSUE THREAD

**Issue by Yansongsongsong** [afatcoder/LeetcodeTop#24]
### 腾讯

- 🔲快排的时间复杂度，最坏的情况描述。
- ✅[两个排序数组找中位数](https://leetcode-cn.com/problems/median-of-two-sorted-arrays/)
- ✅[就数字n的平方根](https://leetcode-cn.com/problems/sqrtx/)
- ✅设计一个算法，抽奖次数越多中奖概率就越高
- ✅[一栋楼有n层，不知道鸡蛋从第几层扔下去会碎，用最少的次数找出刚好会碎的楼层](https://leetcode-cn.com/problems/super-egg-drop/)
- 🔲动态规划与贪心有什么区别
- ✅如何判断一个图是否有环

- - ✅https://leetcode-cn.com/problems/course-schedule/
  - ✅https://leetcode-cn.com/problems/course-schedule-ii/

- ✅[连续整数求和](https://leetcode-cn.com/problems/consecutive-numbers-sum/)
- ✅[给定一个数组，求该数组所有的自子数组](https://leetcode-cn.com/problems/subsets/)
- 🔲给定一个数组，元素的大小0~25，有重复元素。按出现频次的高低输出所有的数字。
- ✅[给定一个二叉树，依次打印出每一行。](https://leetcode-cn.com/problems/cong-shang-dao-xia-da-yin-er-cha-shu-ii-lcof/)

### 字节跳动

- 🔲奇数升序偶数降序，返回升序

- - 🔲https://www.cnblogs.com/DarrenChan/p/8764608.html
  - ✅https://leetcode-cn.com/problems/odd-even-linked-list/
  - ✅https://leetcode-cn.com/problems/reverse-linked-list/
  - ✅https://leetcode-cn.com/problems/merge-two-sorted-lists/

- ✅[LRU](https://leetcode-cn.com/problems/lru-cache/)
- ✅[最大的岛屿面积](https://leetcode-cn.com/problems/max-area-of-island/)。
- ✅[Z字层次遍历二叉树](https://leetcode-cn.com/problems/binary-tree-zigzag-level-order-traversal/)
- ✅[三数之和](https://leetcode-cn.com/problems/3sum/)
- ✅[合并K个排序链表](https://leetcode-cn.com/problems/merge-k-sorted-lists/)。
- ✅[一个无序数组找其子序列构成的和最大，要求子序列中的元素在原数组中两两都不相邻](https://leetcode.com/problems/house-robber/)
- ✅[缺失的第一个正数（leetcode第41题）](https://leetcode-cn.com/problems/first-missing-positive/)
- ✅[现有一个随机数生成器可以生成0到4的数，现在要让你用这个随机数生成器生成0到6的随机数，要保证生成的数概率均匀。](https://leetcode-cn.com/problems/implement-rand10-using-rand7/)
- 🔲 有 N 枚棋子，每个人一次可以拿1到 M 个，谁拿完后棋子的数量为0谁就获胜。现在有1000颗棋子，每次最多拿8个，A 先拿，那么 A 有必胜的拿法吗？第一个人拿完后剩余棋子的数量是8的倍数就必胜，否则就必输。 

- - 🔲https://leetcode-cn.com/problems/stone-game/
  - ✅https://leetcode-cn.com/problems/na-ying-bi/
  - 🔲https://leetcode-cn.com/problems/stone-game-ii/
  - 🔲https://leetcode-cn.com/problems/stone-game-iii/
  - 🔲https://leetcode-cn.com/problems/stone-game-iv/

- ✅[ 给出一棵二叉树的根节点，现在有这个二叉树的部分节点，要求这些节点最近的公共祖先。](https://leetcode-cn.com/problems/lowest-common-ancestor-of-a-binary-tree/)
- ✅[leetcode 394](https://leetcode-cn.com/problems/decode-string/)
- 🔲有序数组，判断平方不相等的数的个数

- - ✅https://leetcode-cn.com/problems/squares-of-a-sorted-array/
  - ✅https://leetcode-cn.com/problems/single-element-in-a-sorted-array/
  - 🔲https://leetcode-cn.com/problems/single-number/

- 🔲[**leetcode 10**](https://leetcode-cn.com/problems/regular-expression-matching/)

### 最右

1. [层次遍历二叉树，返回一个二维数组，每行表示一层](https://leetcode-cn.com/problems/binary-tree-level-order-traversal/)
2. 十万行二维数组，每行长度为10，每个数组降序，找出最大的15个数
3. [最长公共子序列](https://leetcode-cn.com/problems/longest-common-subsequence/)

### 图森未来

1. [方程求根](https://leetcode-cn.com/problems/sqrtx/solution/)
2. https://leetcode-cn.com/problems/jump-game-ii/

### 快手

1. 散列表、哈希算法，如何处理哈希冲突
2. [反转链表](https://leetcode-cn.com/problems/reverse-linked-list/)
3. https://leetcode-cn.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/
4. [数组中的第K个最大元素](https://leetcode-cn.com/problems/kth-largest-element-in-an-array)
5. [最大的岛屿面积](https://leetcode-cn.com/problems/max-area-of-island/)。
6. [原地对链表排序](https://leetcode-cn.com/problems/insertion-sort-list/)
7. [leetcode](https://www.nowcoder.com/jump/super-jump/word?word=leetcode) 2

1. 1. https://leetcode.com/problems/basic-calculator-ii/
   2. https://leetcode-cn.com/problems/add-two-numbers/

1. [求N内的所有素数；](https://leetcode-cn.com/problems/count-primes/)
2. [给定一个乱序数组，求数组内最大连续的数；](https://leetcode-cn.com/problems/maximum-subarray/)
3. [LRU](https://leetcode-cn.com/problems/lru-cache/)
4. [Leetcode 470](https://leetcode-cn.com/problems/implement-rand10-using-rand7/)

**Comment by Yansongsongsong** [comment]
来源是牛客，原始链接散逸了。但是是个人整理的

**Comment by Yansongsongsong** [comment]
链接补充在下面了
🔲https://www.nowcoder.com/discuss/421886
✅https://www.nowcoder.com/discuss/425251
✅https://www.nowcoder.com/discuss/427290
✅https://www.nowcoder.com/discuss/432917
✅https://www.nowcoder.com/discuss/439429
✅https://www.nowcoder.com/discuss/400817
✅https://www.nowcoder.com/discuss/336659
✅https://www.nowcoder.com/discuss/455638
✅https://www.nowcoder.com/discuss/455545
✅https://www.nowcoder.com/discuss/455876
✅https://www.nowcoder.com/discuss/488189
✅https://www.nowcoder.com/discuss/452443
✅https://www.nowcoder.com/discuss/447116
✅https://www.nowcoder.com/discuss/444581
✅https://www.nowcoder.com/discuss/444301
🔲https://www.nowcoder.com/discuss/455369
✅https://www.nowcoder.com/discuss/201045
✅https://www.nowcoder.com/discuss/309103

**Comment by afatcoder** [comment]
> ### 腾讯
> * 🔲快排的时间复杂度，最坏的情况描述。
> * ✅[两个排序数组找中位数](https://leetcode-cn.com/problems/median-of-two-sorted-arrays/)
> * ✅[就数字n的平方根](https://leetcode-cn.com/problems/sqrtx/)
> * ✅设计一个算法，抽奖次数越多中奖概率就越高
> * ✅[一栋楼有n层，不知道鸡蛋从第几层扔下去会碎，用最少的次数找出刚好会碎的楼层](https://leetcode-cn.com/problems/super-egg-drop/)
> * 🔲动态规划与贪心有什么区别
> * ✅如何判断一个图是否有环
> * * ✅https://leetcode-cn.com/problems/course-schedule/
>   * ✅https://leetcode-cn.com/problems/course-schedule-ii/
> * ✅[连续整数求和](https://leetcode-cn.com/problems/consecutive-numbers-sum/)
> * ✅[给定一个数组，求该数组所有的自子数组](https://leetcode-cn.com/problems/subsets/)
> * 🔲给定一个数组，元素的大小0~25，有重复元素。按出现频次的高低输出所有的数字。
> * ✅[给定一个二叉树，依次打印出每一行。](https://leetcode-cn.com/problems/cong-shang-dao-xia-da-yin-er-cha-shu-ii-lcof/)
> 
> ### 字节跳动
> * 🔲奇数升序偶数降序，返回升序
> * * 🔲https://www.cnblogs.com/DarrenChan/p/8764608.html
>   * ✅https://leetcode-cn.com/problems/odd-even-linked-list/
>   * ✅https://leetcode-cn.com/problems/reverse-linked-list/
>   * ✅https://leetcode-cn.com/problems/merge-two-sorted-lists/
> * ✅[LRU](https://leetcode-cn.com/problems/lru-cache/)
> * ✅[最大的岛屿面积](https://leetcode-cn.com/problems/max-area-of-island/)。
> * ✅[Z字层次遍历二叉树](https://leetcode-cn.com/problems/binary-tree-zigzag-level-order-traversal/)
> * ✅[三数之和](https://leetcode-cn.com/problems/3sum/)
> * ✅[合并K个排序链表](https://leetcode-cn.com/problems/merge-k-sorted-lists/)。
> * ✅[一个无序数组找其子序列构成的和最大，要求子序列中的元素在原数组中两两都不相邻](https://leetcode.com/problems/house-robber/)
> * ✅[缺失的第一个正数（leetcode第41题）](https://leetcode-cn.com/problems/first-missing-positive/)
> * ✅[现有一个随机数生成器可以生成0到4的数，现在要让你用这个随机数生成器生成0到6的随机数，要保证生成的数概率均匀。](https://leetcode-cn.com/problems/implement-rand10-using-rand7/)
> * 🔲 有 N 枚棋子，每个人一次可以拿1到 M 个，谁拿完后棋子的数量为0谁就获胜。现在有1000颗棋子，每次最多拿8个，A 先拿，那么 A 有必胜的拿法吗？第一个人拿完后剩余棋子的数量是8的倍数就必胜，否则就必输。
> * * 🔲https://leetcode-cn.com/problems/stone-game/
>   * ✅https://leetcode-cn.com/problems/na-ying-bi/
>   * 🔲https://leetcode-cn.com/problems/stone-game-ii/
>   * 🔲https://leetcode-cn.com/problems/stone-game-iii/
>   * 🔲https://leetcode-cn.com/problems/stone-game-iv/
> * ✅[ 给出一棵二叉树的根节点，现在有这个二叉树的部分节点，要求这些节点最近的公共祖先。](https://leetcode-cn.com/problems/lowest-common-ancestor-of-a-binary-tree/)
> * ✅[leetcode 394](https://leetcode-cn.com/problems/decode-string/)
> * 🔲有序数组，判断平方不相等的数的个数
> * * ✅https://leetcode-cn.com/problems/squares-of-a-sorted-array/
>   * ✅https://leetcode-cn.com/problems/single-element-in-a-sorted-array/
>   * 🔲https://leetcode-cn.com/problems/single-number/
> * 🔲[**leetcode 10**](https://leetcode-cn.com/problems/regular-expression-matching/)
> 
> ### 最右
> 1. [层次遍历二叉树，返回一个二维数组，每行表示一层](https://leetcode-cn.com/problems/binary-tree-level-order-traversal/)
> 2. 十万行二维数组，每行长度为10，每个数组降序，找出最大的15个数
> 3. [最长公共子序列](https://leetcode-cn.com/problems/longest-common-subsequence/)
> 
> ### 图森未来
> 1. [方程求根](https://leetcode-cn.com/problems/sqrtx/solution/)
> 2. https://leetcode-cn.com/problems/jump-game-ii/
> 
> ### 快手
> 1. 散列表、哈希算法，如何处理哈希冲突
> 2. [反转链表](https://leetcode-cn.com/problems/reverse-linked-list/)
> 3. https://leetcode-cn.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/
> 4. [数组中的第K个最大元素](https://leetcode-cn.com/problems/kth-largest-element-in-an-array)
> 5. [最大的岛屿面积](https://leetcode-cn.com/problems/max-area-of-island/)。
> 6. [原地对链表排序](https://leetcode-cn.com/problems/insertion-sort-list/)
> 7. [leetcode](https://www.nowcoder.com/jump/super-jump/word?word=leetcode) 2
> 8. 1. https://leetcode.com/problems/basic-calculator-ii/
>    2. https://leetcode-cn.com/problems/add-two-numbers/
> 9. [求N内的所有素数；](https://leetcode-cn.com/problems/count-primes/)
> 10. [给定一个乱序数组，求数组内最大连续的数；](https://leetcode-cn.com/problems/maximum-subarray/)
> 11. [LRU](https://leetcode-cn.com/problems/lru-cache/)
> 12. [Leetcode 470](https://leetcode-cn.com/problems/implement-rand10-using-rand7/)

哇，非常您的感谢分享！！我去加一下

**Comment by afatcoder** [comment]
哇，感谢分享，我去加一下。
ps：字节跳动的🔲奇数升序偶数降序，返回升序 确实在力扣上找不到，但却是常考题，目前已加到补充题系列中了。[字节跳动高频题之排序奇升偶降链表](https://zhuanlan.zhihu.com/p/311113031)

**Comment by wenbochang888** [comment]
感谢分享
