### ISSUE TITLE
[建议] 建议加入是否已做过该题目

### ISSUE THREAD

**Issue by wenbochang888** [afatcoder/LeetcodeTop#25]
- 首先感谢作者的无私奉献，star，fork已贡献
- <a href = "https://leetcode-cn.top/#/home">codeTope</a>网站能否加入leetcode登陆，那么就可以判断是否做过该题。下次打开我好判断从哪里开始做题，非常感谢。

**Comment by wenbochang888** [comment]
类似于leetcode，前面有个小勾勾

**Comment by ErazerControl** [comment]
> * 首先感谢作者的无私奉献，star，fork已贡献
> * [codeTope](https://leetcode-cn.top/#/home)网站能否加入leetcode登陆，那么就可以判断是否做过该题。下次打开我好判断从哪里开始做题，非常感谢。

leetcode没有提供oAuth登录的接口，因此没办法支持leetcode登录。我倒是可以加个做题记录的功能，不过需要用户手动点击此题是否做过。

**Comment by afatcoder** [comment]
> * 首先感谢作者的无私奉献，star，fork已贡献
> * [codeTope](https://leetcode-cn.top/#/home)网站能否加入leetcode登陆，那么就可以判断是否做过该题。下次打开我好判断从哪里开始做题，非常感谢。

leetcode没有提供oAuth登录的接口，因此没办法支持leetcode登录。我倒是可以加个做题记录的功能，不过需要用户手动点击此题是否做过。

**Comment by wenbochang888** [comment]
> > * 首先感谢作者的无私奉献，star，fork已贡献
> > * [codeTope](https://leetcode-cn.top/#/home)网站能否加入leetcode登陆，那么就可以判断是否做过该题。下次打开我好判断从哪里开始做题，非常感谢。
> 
> leetcode没有提供oAuth登录的接口，因此没办法支持leetcode登录。我倒是可以加个做题记录的功能，不过需要用户手动点击此题是否做过。

如果没有提供OAuth接口，比较麻烦。第二种如果用户需求不大的话，可以评估下工作量来衡量，最后还是感谢分享
