### ISSUE TITLE
[建议] 能否添加每道题所对应到的面经的跳转链接？

### ISSUE THREAD

**Issue by zh-Spike** [afatcoder/LeetcodeTop#35]
首先感谢afatcoder搭建网站。

我朋友在准备面试算法时就连碰两道题库中的高频题，个人建议题目可以加入跳转到对应面经的功能，这样能更有针对性的准备面试。

**Comment by afatcoder** [comment]
非常感谢你的建议，未来此功能会考虑加入在CodeTop中~
