### ISSUE TITLE
codetop.cc is down ?

### ISSUE THREAD

**Issue by pangjac** [afatcoder/LeetcodeTop#51]
![image](https://user-images.githubusercontent.com/13987136/140955698-12ac32d4-e9a6-4d7a-9c7e-06c8fd72dfb8.png)

Hi,
请问codetop.cc 是挂了吗 ? 还是外网打不开?  谢谢!

**Comment by ErazerControl** [comment]
没有挂，外网好像打不开...之后我会在国外服务器部署下，如果好了会在这个issue更新

**Comment by afatcoder** [comment]
没有挂，外网好像打不开...之后我会在国外服务器部署下，如果好了会在这个issue更新

**Comment by pangjac** [comment]
For engineers working abroad, you have to use VPN to traffic back. I used VPN and it works.    Thank op for the support and quickly response!
