### ISSUE TITLE
更新国区力扣链接

### ISSUE THREAD

**Issue by monster898** [afatcoder/LeetcodeTop#58]
力扣网址从 `https://leetcode-cn.com/` 变更为 `https://leetcode.cn/`,  现在访问老网址每次都要confirm来能跳转。

**Comment by Misaka11** [comment]
已收到您发的邮件。本邮件是自动回复。

**Comment by afatcoder** [comment]
感谢提醒。这两天把 CodeTop网站 https://codetop.cc 的链接都更新了，GitHub 仓库的链接还没有更新。

**Comment by monster898** [comment]
Thanks so much for your great work!
