### ISSUE TITLE
[ bug?]网页版的原创模块访问不到了，但是微信小程序可以

### ISSUE THREAD

**Issue by siren-xiaohu** [afatcoder/LeetcodeTop#65]

**Comment by Misaka11** [comment]
已收到您发的邮件。本邮件是自动回复。

**Comment by afatcoder** [comment]
不是的，原创模块访问量不多，我下线了，小程序过段时间该功能也会下线。

**Comment by siren-xiaohu** [comment]
好滴



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月03日 07:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [afatcoder/LeetcodeTop] [ bug?]网页版的原创模块访问不到了，但是微信小程序可以 (Issue #65) |

不是的，原创模块访问量不多，我下线了，小程序过段时间该功能也会下线。
