### ISSUE TITLE
这个仓库不维护了么

### ISSUE THREAD

**Issue by qzqsmile** [afatcoder/LeetcodeTop#66]
RT

**Comment by kabuda001** [comment]
我感觉已经没有维护了

**Comment by afatcoder** [comment]
https://codetop.cc网站的数据还在更新，只是好久没有把网站的数据同步在github

**Comment by qzqsmile** [comment]
感觉行情太差，都没啥维护的必要了 😅

**Comment by SpongeBab** [comment]
确实，
![image](https://github.com/afatcoder/LeetcodeTop/assets/65898238/e428af45-1b35-45fa-8fb3-6228ea92746a)
最近考察时间证明网站在运营，而且已经有付费业务。github 估计没有人力维护。
