### ISSUE TITLE
登录验证的按钮找不到了

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [afatcoder/LeetcodeTop#68]
![image](https://github.com/afatcoder/LeetcodeTop/assets/26433572/3d19abf1-83c9-45a3-82f9-837dfad35260)

![image](https://github.com/afatcoder/LeetcodeTop/assets/26433572/cb1ed973-4974-49d3-8f13-c91561c0fcc0)

**Comment by Misaka11** [comment]
已收到您发的邮件。本邮件是自动回复。

**Comment by yunCrush** [comment]
+1

**Comment by charfole** [comment]
@afatcoder

**Comment by EricOo0** [comment]
+1找不到按钮

**Comment by zhangmingdi** [comment]
+1 无按钮

**Comment by AttackXiaoJinJin** [comment]
最新消息

![IMG_0667](https://github.com/afatcoder/LeetcodeTop/assets/26433572/c419fb7f-188a-4318-9838-664916283fd3)

**Comment by AttackXiaoJinJin** [comment]
看到恢复了，故close
