### ISSUE TITLE
笑死 , 我还需要你给我提供题目资源吗?  还能太水一点吗

### ISSUE THREAD

**Issue by super117893344p** [afatcoder/LeetcodeTop#73]

**Comment by SpongeBab** [comment]
大可不必阴阳怪气。你可以fork 一个仓库，继续更新，I will star.

**Comment by afatcoder** [comment]
我没太理解你的意思。
[CodeTop网站](https://codetop.cc)的数据一直在更新，只是我没有同步在github仓库里
