### ISSUE TITLE
hot100题目是否正确

### ISSUE THREAD

**Issue by lzxqwq** [afatcoder/LeetcodeTop#78]
为啥codetop上的hot100和leetcode上的hot100题目不完全一致？

**Comment by Misaka11** [comment]
已收到您发的邮件。本邮件是自动回复。

**Comment by lzxqwq** [comment]
咱就是说，能不能改改啊，和力扣上的hot100题单对不上啊

**Comment by Misaka11** [comment]
已收到您发的邮件。本邮件是自动回复。
