### ISSUE TITLE
希望加入各公司汇总去重后的结果

### ISSUE THREAD

**Issue by yzt95** [afatcoder/LeetcodeTop#8]
希望汇总所有公司和岗位的题目，然后做个题目去重和频率加和，感觉是个大工程😂

**Comment by afatcoder** [comment]
我暂时没有把所有公司的数据汇总到一个排名的想法，因为不同公司的题目数量是不同的，这样累加起来是有失公允的。

如果你当前确实需要所有公司的题目排名，现在codetop小程序有个feature，可以不输入关键字搜索，即所有公司考察算法题的榜单，之后可能会考虑废弃这个feature。

![codetop](https://note.youdao.com/yws/public/resource/a9216f577fb9d322425561dfea9188bc/xmlnote/056AEE2B592D460B99BEB2BEF1538A54/10782)

**Comment by yzt95** [comment]
好的，谢谢，我去看一下

**Comment by afatcoder** [comment]
> 好的，谢谢，我去看一下

新开发了网站，https://leetcode-cn.top/
这次应该更满足您的需求啦
